# Generated by Django 5.2.3 on 2025-06-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_total_amount_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
