# Generated by Django 5.2.3 on 2025-06-27 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_order_product_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.brand'),
            preserve_default=False,
        ),
    ]
